const KiaSonetArray = [
    {
        id:1,
        ProductName:"Carpet Mat",
        ProductImg:"https://www.jiomart.com/images/product/original/rvjavy5hci/carbinic-7d-luxury-car-foot-mat-custom-fitted-for-toyota-innova-crysta-7-layer-protection-double-diamond-cut-stitching-waterproof-dust-proof-anti-skid-car-accessories-black-product-images-orvjavy5hci-p600706592-0-202304191855.jpg?im=Resize=(1000,1000)",
        ProductPrice:200,
        ProductDescription:"Wild Outside. Peaceful inside. Smart Pure Air Purifier with Virus & Bacteria Protection* The New Kia Sonet 2024 | The Wild. Reborn. Price starts at ₹7 99 000*, Book Now. Tiger Nose Grille. Star Map LED DRLs. New-age Design. All Wheel Disk Breaks. Models: HTE, HTK.",
    },
    {
        id:2,
        ProductName:" 3D Cabin Mat",
        ProductImg:"https://www.motorbhp.com/image/cache/catalog/product/life%20long%20mats/sonet-3d-cabin-mat-1000x1000.jpg.webp",
        ProductPrice:2800,
        ProductDescription:"Wild Outside. Peaceful inside. Smart Pure Air Purifier with Virus & Bacteria Protection* The New Kia Sonet 2024 | The Wild. Reborn. Price starts at ₹7 99 000*, Book Now. Tiger Nose Grille. Star Map LED DRLs. New-age Design. All Wheel Disk Breaks. Models: HTE, HTK.",
    },
    {
        id:3,
        ProductName:" 3D trunk Mat",
        ProductImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqNaDWRo2gHryo2tRaizLXnIgVVz9AaatXEVSIndCBFQ&s",
        ProductPrice:1885,
        ProductDescription:"eneric Name: Boot Mat. Description. Automat 3D boot mat is designed to keep the floor of your vehicle in pristine condition. With its raised edges dust, dirt ..",
    },
    {
        id:4,
        ProductName:"Dual Layere Mat",
        ProductImg:"https://www.motorbhp.com/image/cache/catalog/product/life%20long%20mats/sonet-3d-cabin-mat-1000x1000.jpg.webp",
        ProductPrice:5151,
        ProductDescription:"Hi Art PVC, Faux Leather, Nylon 7D Car Floor Mats Compatible with Kia Sonet (2020-2024), (Black) : Amazon.in: Car & Motorbike.",
    },
    {
        id:5,
        ProductName:" Full Floor Mat",
        ProductImg:"https://www.hotcarshop.in/images/Products/220720224876.jpg",
        ProductPrice:3485,
        ProductDescription:"These mats are custom made according to each car model and covers up the full floors along with the side walls. Both lower leatherette layer & upper grass ",
    },
    {
        id:6,
        ProductName:" Car Cover - Standard",
        ProductImg:"https://m.media-amazon.com/images/I/61ZCJcD7oxL._AC_UF1000,1000_QL80_.jpg",
        ProductPrice:1531,
        ProductDescription:"With Mirror Pockets · Water Repellant · Material: Matty, Polyutherine · Tear Resistant, UV Ray Protection, Water Resistant, Weather Resistant · Universal Fit.",
    },
    {
        id:7,
        ProductName:" Head Lamp Garnish Chrome",
        ProductImg:"https://m.media-amazon.com/images/I/41Lpz9NFReL.jpg",
        ProductPrice:999,
        ProductDescription:"This Head-lamp garnish is custom-made and fits precisely on KIA Sonet headlamps. It is made of high-quality flexible ABS plastic with a Chrome finish. The product is manufactured and sold by Galio. The packing consists of a two-piece set.",
    },
    {
        id:8,
        ProductName:"tail lamp garnish chrome",
        ProductImg:"https://carhatke.com/image/cache/catalog/catalog-new-images/sonet-tail-lamp-chrome-500x500.jpg",
        ProductPrice:1299,
        ProductDescription:"It is applied on the corners or edges of the vehicle's tail lamps. This Tail-lamp garnish is custom-made and fits precisely on KIA Sonet taillamps",
    },
    {
        id:9,
        ProductName:" ORVM Garnish Chrome",
        ProductImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIVtg0LBrn4e6SqvoLlY1u9jy5Sr7v7ExWV2tlPZ5NKQ&s",
        ProductPrice:1299,
        ProductDescription:"Sonet ORVM Garnish. Chrome finish mirror covers make a premium eye-catching addition to your vehicle. For cars with integrated indicators. Set of 2.",
    },
    {
        id:10,
        ProductName:"Fog Lamp Garnish Chrome",
        ProductImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStRETNvxi6Wy85mg-xtHEqPVZDepOgPRm_JXx75WS3_Q&s",
        ProductPrice:629,
        ProductDescription:"This Head-lamp garnish is custom-made and fits precisely on KIA Sonet headlamps. It is made of high-quality flexible ABS plastic with a Chrome finish. The product is manufactured and sold by Galio.",
    },
    {
        id:11,
        ProductName:" Door Handle Chrome",
        ProductImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs2v5uU_Q-v4EirosacFoIFIU-y7WnVgKpomRw3Ef6oA&s",
        ProductPrice:903,
        ProductDescription:"Chrome Plated Door Handle Cover is for the protection of your car's door handles from the daily grind of opening and closing the doors.",
    },
    {
        id:12,
        ProductName:" Finger Guard Chrome",
        ProductImg:"https://www.jiomart.com/images/product/original/rvkwdxpf0b/falcon-car-finger-guard-chrome-for-sonet-2020-onwards-product-images-orvkwdxpf0b-p597507706-1-202301120444.jpg?im=Resize=(420,420)",
        ProductPrice:899,
        ProductDescription:"Our FINGER GARD is made with the best material and proper thickness of Chrome. Because of that, your car gets a stunning and enhanced look.",
    },
    {
        id:13,
        ProductName:" Wheel Arch Garnish Chrome",
        ProductImg:"https://www.motorbhp.com/image/cache/catalog/products/baleno-wheel-arch-chrome_2-550x550w.jpg.webp",
        ProductPrice:1799,
        ProductDescription:"Sonet Wheel Arc Garnish. Unique chrome highlights for wheel arch. Precision design to give an exclusive look. Part Number. CCR46IN002. Category.",
    },
    {
        id:14,
        ProductName:" Body Side Moulding Chrome",
        ProductImg:"https://m.media-amazon.com/images/I/41CWS0hVyRL._AC_UF1000,1000_QL80_.jpg",
        ProductPrice:1990,
        ProductDescription:"the Kia Sonet Body Side Moulding Chrome protects against scratches, scuffs, and minor impacts. Its durable construction ensures that your car remains in pristine condition, preserving its resale value.",
    },
    {
        id:15,
        ProductName:" Number Plate Garnish",
        ProductImg:"https://images.meesho.com/images/products/271116693/ojkb2_512.webp",
        ProductPrice:799,
        ProductDescription:"Highly Durable With Triple Layer Chrome Finish. Easy Installation, Comes With Adhesive Tape. Imported Product With High-Quality Chrome Finish.",
    },
    {
        id:16,
        ProductName:" Window Beading Chrome",
        ProductImg:"https://m.media-amazon.com/images/I/61zR20LtFCL.jpg",
        ProductPrice:1203,
        ProductDescription:"These lower window chrome garnishes made out of stainless steel material with a triple-layer chrome finish. Purpose to the install this chrome garnish trim is ...",
    }, {
        id:17,
        ProductName:" Twin Color Door Sill Guard",
        ProductImg:"https://carhatke.com/image/catalog/catalog-new-images/Foot%20Step/led/kia-sonet-led-foot-step-scuff-plate-4.jpg",
        ProductPrice:778,
        ProductDescription:"Door sill plate help protect the interior door sills from scratches, ... company fitted double sided adhesive tape. Protects the door, rust free long lasting also ....",
    }, {
        id:18,
        ProductName:"Bumper Protectors",
        ProductImg:"https://carhatke.com/image/catalog/catalog-new-images/bumper-protector/kia-sonet-oem-type-bumper-protector-guard-set-of4.jpg",
        ProductPrice:770,
        ProductDescription:"Ant Enterprize car bumper protector guard protect your car from scratches, dents and give your car extra life. Important : DO NOT USE THE ADHESIVE ON POLISHED ...",
    },
    {
        id:19,
        ProductName:" Door Edge Guard",
        ProductImg:"https://m.media-amazon.com/images/I/41ADLSBT13L._AC_UF1000,1000_QL80_.jpg",
        ProductPrice:350,
        ProductDescription:"It protects the car door against minor scratches and dents in tight spots; Strong 3M adhesive tape for easy sticking; Long lasting and durable material ....",
    },
    {
        id:20,
        ProductName:"Head light",
        ProductImg:"https://5.imimg.com/data5/SELLER/Default/2022/1/PP/FD/CA/126413572/kia-sonet-headlight-1000x1000.jpeg",
        ProductPrice:2800,
        ProductDescription:"YK & Company - Offering White LED Kia Sonet Headlight, Right & Left at Rs 9000/piece in New Delhi, Delhi. Get Car Headlight at lowest price",
    },
    {
        id:21,
        ProductName:"Door Panel",
        ProductImg:"https://imgd.aeplcdn.com/370x208/n/cw/ec/141383/sonet-interior-rear-door-pad.jpeg?isig=0&q=80",
        ProductPrice:7000,
        ProductDescription:"Wild Outside. Peaceful inside. Smart Pure Air Purifier with Virus & Bacteria Protection* The New Kia Sonet 2024 | The Wild. Reborn. Price starts at ₹7 99 000*, Book Now. Tiger Nose Grille. Star Map LED DRLs. New-age Design. All Wheel Disk Breaks. Models: HTE, HTK.",
    },
    {
        id:22,
        ProductName:" Steering Wheel",
        ProductImg:"https://imgd.aeplcdn.com/370x208/n/cw/ec/174423/sonet-interior-steering-wheel.jpeg?isig=0&q=80",
        ProductPrice:8000,
        ProductDescription:"System layout – steering wheel remote control · MUTE button. Press to mute or unmute the system. · MODE button. Press to switch between radio and media modes.",
    },
    {
        id:23,
        ProductName:"Dashboard",
        ProductImg:"https://imgd.aeplcdn.com/370x208/n/cw/ec/174423/sonet-interior-dashboard.jpeg?isig=0&q=80",
        ProductPrice:15000,
        ProductDescription:"Kia vehicles are equipped with various warning indicators and lights to alert the driver about specific issues or conditions.",
    },
    {
        id:24,
        ProductName:"Instrument Cluster",
        ProductImg:"https://imgd.aeplcdn.com/370x208/n/cw/ec/141383/sonet-interior-instrument-cluster.jpeg?isig=0&q=80",
        ProductPrice:8000,
        ProductDescription:"Instrument cluster · Tachometer · Speedometer · Engine coolant temperature gauge · Fuel gauge · Warning and indicator lights · LCD display.",
    },
    {
        id:25,
        ProductName:"Gear Shifter/Gear Shifter Stalk ",
        ProductImg:"https://imgd.aeplcdn.com/370x208/n/cw/ec/141383/sonet-interior-gear-shifter-gear-shifter-stalk.jpeg?isig=0&q=80",
        ProductPrice:1075,
        ProductDescription:"System designed to improve car stability and control, especially when the car is accelerating. ESP or ESC cannot increase traction but rather improve control or ...",
    },
    {
        id:26,
        ProductName:" Center Console/Centre Console Storage",
        ProductImg:"https://imgd.aeplcdn.com/370x208/n/cw/ec/141383/sonet-interior-center-console-centre-console-storage.jpeg?isig=0&q=80",
        ProductPrice:1800,
        ProductDescription:"Increasingly, center consoles include a wide variety of storage compartments and cupholders, some of them with a refrigerator, in addition to the more traditional use as purely a surface for instrumentation (e.g., outside temperature display) and controls (car audio).",
    },
   
   
]

export default KiaSonetArray;