const SuzikiArrayparts = [
    {
        id:1,
        ProductName:"GLOW PLUG",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/new-images/18550m86j00/18550m86j00_2.jpg",
        ProductPrice:715,
        ProductDescription:"A glow plug is a heating element that heats incoming fuel and air to encourage efficient fuel combustion in a diesel engine.",
    },
    {
        id:2,
        ProductName:"RADIATOR ASSEMBLY",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/new-images/17700m74l50/17700m74l50_1_t.jpg",
        ProductPrice:4250,
        ProductDescription:"When you buy Radiator / Intercooler Assembly & its components of Maruti Suzuki you get the MSGP Advanatge of Reliability & Efficiency",
    },
    {
        id:3,
        ProductName:"FAN ASSEMBLY- ENGINE COOLING",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/new-images/17100m79m03/17100m79m03_1.jpg",
        ProductPrice:5260,
        ProductDescription:"When you buy Radiator / Intercooler Assembly & its components by Maruti Suzuki you get the MSGP Advanatge of Reliability & Efficiency",
    },
    {
        id:4,
        ProductName:"OIL FILTER",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/new-images/16510m86j20/16510m86j20_1.jpg",
        ProductPrice:385,
        ProductDescription:"Very minute solid particles (contaminants) get mixed with engine oil due to wear and tear, rotating engine parts & combustion suit. Oil filters separate out these contaminants from engine oil and keeps it clean.",
    },
    {
        id:5,
        ProductName:"OIL FILTER",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/new-images/16510m83m00/16510m83m00_1.jpg",
        ProductPrice:175,
        ProductDescription:"Very minute solid particles (contaminants) get mixed with engine oil due to wear and tear, rotating engine parts & combustion suit. Oil filters separate out these contaminants from engine oil and keeps it clean.",
    },
    {
        id:6,
        ProductName:"FUEL FILTER",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/new-images/15412m86j00/15412m86j00_1_t.jpg",
        ProductPrice:1350,
        ProductDescription:"uel quality varies across India based on geographic location. Fuel filter is used in vehicles to ensure clean fuel operation in engine.",
    },
    {
        id:7,
        ProductName:"FUEL FILTER ASSEMBLY",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/photoshoot-images/black/15410m68p00/15410m68p00_1.png",
        ProductPrice:275,
        ProductDescription:"Fuel quality varies across India based on geographic location. Fuel filter is used in vehicles to ensure clean fuel operation in engine",
    },
    {
        id:8,
        ProductName:"SERVICE KIT, NEW SWIFT PETROL",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/photoshoot-images/black/99000m24120-776/99000m24120-776_1.png",
        ProductPrice:1150,
        ProductDescription:"Part Kits by Maruti Suzuki bring more value for your money and superior quality",
    },
    {
        id:9,
        ProductName:"TOOL ASSY",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/2022/01/89960m66r00/89960m66r00_1.jpg",
        ProductPrice:365,
        ProductDescription:"Do it yourself tools come in handy during vehicle breakdown, so always Choose Genuine products from Maruti Suzuki",
    },
    {
        id:10,
        ProductName:"OIL FILTER",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/new-images/16510m68k10/16510m68k10_1.jpg",
        ProductPrice:95,
        ProductDescription:"Very minute solid particles (contaminants) get mixed with engine oil due to wear and tear, rotating engine parts & combustion suit. Oil filters se",
    },
    {
        id:11,
        ProductName:"AIR FILTER",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/photoshoot-images/black/13780m86j00/13780m86j00_1.png",
        ProductPrice:275,
        ProductDescription:"Air Filters prevent harmful contaminants from entering the engine and ensures a good mixture of air and fuel to support performance.",
    },

    {
        id:12,
        ProductName:"BELT-WATER PUMP",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/new-images/17521m53m00/17521m53m00_1.jpg",
        ProductPrice:159,
        ProductDescription:"Water Pump Belt ensure proper functioning of Accessories which it drives such as Alternator and Water Pump.",
    },
    {
        id:13,
        ProductName:"FUEL FILTER",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/new-images/15411m55kd0/15411m55kd0_1_t.jpg",
        ProductPrice:1220,
        ProductDescription:"Fuel quality varies across India based on geographic location. Fuel filter is used in vehicles to ensure clean fuel operation in engine.",
    },
    {
        id:14,
        ProductName:"BRAKE FLUID GC 1500AA (250 ML PACK)",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/photoshoot-images/estar/99000m24120-580/99000m24120-580_1.png",
        ProductPrice:190,
        ProductDescription:"Brake fluids are responsible for ensuring smooth movement of various components of braking components.        ",
    },
    {
        id:15,
        ProductName:"Spark Plug",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/photoshoot-images/color/09482m00609/09482m00609_1.jpg",
        ProductPrice:115,
        ProductDescription:"Spark plug is a critical engine component that provides the spark that ignites the air-fuel mixture that drives an engine.        ",
    },
    {
        id:16,
        ProductName:"UNIT HEAD LAMP (RIGHT)",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/new-images/35121m55rb0/35121m55rb0_1.jpg",
        ProductPrice: 21310,
        ProductDescription:"Illuminate the road ahead with genuine Head Lamps, Fog lamps and Bulbs. Always insist on buying Maruti Suzuki Genuine Parts",
    },

    {
        id:17,
        ProductName:"STEERING WHEEL ASSEMBLY",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/2023/04/02/48110m55r30-hlf/48110m55r30-hlf_1.jpg",
        ProductPrice:4845,
        ProductDescription:"MSGP Steering Assemblies and components make it easier to turn and steer the vehicle accurately",
    },

    {
        id:18,
        ProductName:"FRONT BUMPER",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/2023/03/02/71711m56r00-5pk/71711m56r00-5pk_1.jpg",
        ProductPrice:1935,
        ProductDescription:"Always insist on genuine Body parts by Maruti Suzuki , body parts that are tailor-made for your vehicle.",
    },
    {
        id:19,
        ProductName:"BOX ASSYSTRG GEAR",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/2023/03/01/48500m55r02/48500m55r02_1.jpg",
        ProductPrice:8700,
        ProductDescription:"MSGP Steering Assemblies and components make it easier to turn and steer the vehicle accurately        ",
    },
    {
        id:20,
        ProductName:"COVER SET_CLUTCH",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/2022/11/09/22011m86j84/22011m86j84_1.jpg",
        ProductPrice:3550,
        ProductDescription:"For powerful, engaging and perfect drives always use genuine Clutch components by Maruti Suzuki        ",
    },
    {
        id:21,
        ProductName:"BULB",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/photoshoot-images/black/09471m12090/09471m12090_1.png",
        ProductPrice:99,
        ProductDescription:"Illuminate the road ahead with genuine Head Lamps, Fog lamps and Bulbs. Always insist on buying Maruti Suzuki Genuine Parts",
    },

    {
        id:22,
        ProductName:"ENGINE-INTER COOLER",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/2023/03/01/13620m60m50/13620m60m50_1.jpg",
        ProductPrice:5800,
        ProductDescription:"When you buy Radiator / Intercooler Assembly & its components by Maruti Suzuki you get the MSGP Advanatge of Reliability & Efficiency",
    },
    {
        id:23,
        ProductName:"BEARING_CLUTCH RELEASE",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/2023/05/07/23265m79f00/23265m79f00_1.jpg",
        ProductPrice:605,
        ProductDescription:"For powerful, engaging and perfect drives always use genuine Clutch components by Maruti Suzuki",
    },
    {
        id:24,
        ProductName:"BRAKE PAD SET",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/2022/04/15/55810m79f10/55810m79f10_1.jpg",
        ProductPrice:2430,
        ProductDescription:"Braking Components & Assemblies by Maruti Suzuki Genuine Parts ensure Safe Driving for your vehicle",
    },
    {
        id:25,
        ProductName:"REAR WINDSHIELD GLASS",
        ProductImg:"https://marutisuzukiarenaprodcdn.azureedge.net/-/media/msgp/parts-image/new-images/84570m56r00/84570m56r00_1.jpg",
        ProductPrice:3025,
        ProductDescription:"Windshield is critical component for safe & clear vision during your ride, during replacement always insist on Windshield Glass, Glass Moulding and Se",
    },
    {
        id:26,
        ProductName:"Maruti Suzuki logo key cover",
        ProductImg:"https://m.media-amazon.com/images/I/61XrsHxG+3L._AC_UF1000,1000_QL80_.jpg",
        ProductPrice:100,
        ProductDescription:"HATAKE provides you the best car accessories and we have successfully built a strong reputation in the market for delivering good and attractive products. We strive to provide the best possible experience for our customers on e-commerce platform while shopping so they can buy with confidence, knowing that they will receive exactly what they ordered every single time!",
    },
    {
        id:27,
        ProductName:"Sit Cover",
        ProductImg:"https://imgd.aeplcdn.com/370x208/n/cw/ec/115601/2022-xl6-interior-front-row-seats-2.jpeg?isig=0&q=80",
        ProductPrice:5000,
        ProductDescription:"Enhance the interior aesthetics of your car with all seat covers, high quality accessories. Always buy Genuine Accessories directly from Maruti Suzuki.",
    },
    {
        id:28,
        ProductName:"Instrument Cluster",
        ProductImg:"https://imgd.aeplcdn.com/370x208/n/cw/ec/115601/2022-xl6-interior-instrument-cluster.jpeg?isig=0&q=80",
        ProductPrice:6000,
        ProductDescription:"A car's instrument cluster houses the various displays and indicators that enable a driver to operate the vehicle. Among these are several gauges – often a speedometer, odometer, tachometer, oil pressure gauge, fuel gauge, etc",
    },
]

export default SuzikiArrayparts;