const MahendraArray = [
  {
    id: 1,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 2,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 3,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 4,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 5,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },

  {
    id: 6,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 7,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 8,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 9,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },


  {
    id: 10,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 11,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 12,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 13,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 14,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },

  {
    id: 15,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 16,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 17,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },

  {
    id: 18,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 19,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 20,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 21,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },

  {
    id: 22,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 23,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 24,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },

  {
    id: 25,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 26,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 27,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 28,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 29,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },
  {
    id: 30,
    ProductName: " ",
    ProductImg: "",
    ProductPrice: 0,
    ProductDescription: "",
  },

];
export default MahendraArray;
